### ISSUE TITLE
Не работает props "data-test-id" для компонента Input

### ISSUE THREAD

**Issue by NoflexGit** [alfa-laboratory/arui-feather#1019]
## Ожидаемое поведение
Корректно передается props "data-test-id" и отображается в разметке
## Актуальное поведение
Props "data-test-id" передается, но в разметке не отображается дата-аттрибут
## Шаги для воспроизведения
Прокинуть props'у в комопонент, открыть средства разработчика, в разметке компонента отсутствует дата-аттрибут
## Возможное решение

Попробовал откатиться до 14.5.0 - там работает нормально
Судя  #по изменениям, просто убрали использование пропсы в компоненте 
## Окружение

* Используемая версия библиотеки:
16.0.3
* Имя и версия браузера:
Chrome 79.0.3945.130
* Имя и версия ОС:
OSX 10.14.6

**Comment by dmitrbrvsk** [comment]
@NoflexGit эту проблему уже пофиксили в последнем релизе 16.0.4, обнови просто `arui-feather`
[https://github.com/alfa-laboratory/arui-feather/pull/939](url)

**Comment by stepancar** [comment]
@NoflexGit https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=%3CInput%20value='default'%20data-test-id='my-test-id'%20/%3E
работает.
