### ISSUE TITLE
Перевести https://github.com/alfa-laboratory/arui-feather/blob/master/src/lib/scroll-to.js на ts

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#1020]

**Comment by YozhEzhi** [comment]
Тест, наверное, тоже нужно переписать. (ts-jest?)

https://github.com/alfa-laboratory/arui-feather/blob/master/src/lib/scroll-to.js
https://github.com/alfa-laboratory/arui-feather/blob/master/src/lib/scroll-to.test.js

**Comment by doyakovlev** [comment]
@stepancar @YozhEzhi 
Займусь
