### ISSUE TITLE
Темизация компонента Toggle

### ISSUE THREAD

**Issue by Hydrock** [alfa-laboratory/arui-feather#1026]
Нужен дополнительная темизация компонента Toggle
Сейчас он только красный - но в наших дизайнах есть темно синий цвет

## Ожидаемое поведение
Нужна темизация
![image](https://user-images.githubusercontent.com/20814779/73858133-f5636b00-4848-11ea-8659-54614bcf7779.png)

нужен доп цвет задника - #0b1f35; --color-dark-indigo

## Актуальное поведение
Сейчас только красный цвет
![image](https://user-images.githubusercontent.com/20814779/73858548-a1a55180-4849-11ea-9b57-9502cb7a3a51.png)

## Возможное решение
допавить пропс view - повторить темизацию как у кнопки (как пример)
Значение по умолчанию оставить - красное

**Comment by stepancar** [comment]
@SiebenSieben

**Comment by Hydrock** [comment]
Дизайнеры не апрувнули, toggle нужно использовать красный как есть.
