### ISSUE TITLE
Использовать один CI для всего

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#1070]
Сейчас есть пересечение travis и других штуковин. Надо отойти от зоопарка

**Comment by Luchanso** [comment]
Давайте перейдём на github actions. Github Actions пока работает на 10% быстрее, чем travis.

**Comment by stepancar** [comment]
А я предлагаю сначала пренести то что не на travis на него. Удалить лишнее. Опсать что есть и только потом мигрировать взвесив плюсы. Прошла миграция  с тревиса на другую штуку тоже видимо была из за скорости но главное в этом что задача не завершена. и в этом теперь никто не разбирается

**Comment by Luchanso** [comment]
У github CI легче получить доступ - это следующий аргумент

**Comment by Luchanso** [comment]
Теперь эти занимается Марченко Роман

**Comment by IBelyaev** [comment]
Теперь все на GitHun Actions.
