### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#1080]
# Arui-feather MAJOR
## Typescript Migration

Мы полностью мигрировали на typescript то что ранее было описано в propTypes.
Это позволит в дальнейшем отказаться от кода генерации типов из  javascript https://github.com/alfa-laboratory/library-utils/blob/master/typings/stringify-component-definition.js#L4
и упростить процесс сборки либ в целом.
Так же это позволит описывать типы более качественно. Ну а так же позволит получить все прелести разработки на typescript в самом arui-feather.

Важно для вас относительно предыдущих типов - мы перестали экспортить часть типов пропс.

 Было
```
import Button, { ButtonFieldSizeType } from 'arui-feather/button';

let size: ButtonFieldSizeType;
```
Стало
```
import Button, { ButtonProps } from 'arui-feather/button';

let size: ButtonProps['size'];
```
Раньше эти типы генерировались, теперь так как они ровно те, которын мы написали - придется поддерживать такой нейминг. Но мы не можем доверять эту проверку людям. Поэтому мы убираем такую возможность. Но у вас все так же остается возможность достать нужный тип того же качества. Как в примере выше. Просто выглядит это чуть чуть не так.

## @cn -> bem-react-classname

Мы полностью мигрировали c [cn-decorator](https://github.com/alfa-laboratory/cn-decorator) на [bem-react-classname](https://github.com/alfa-laboratory/bem-react-classname)
это позволит перевести arui-private на bem-react-classname и далее заменить решение в приложениях. Сама мотивация bem-react-classname - это тайпскриптовая валидация внутри компонента и возможность использовать в функциональных компонентах.
Мы просто разблокируем в этом релизе использование одного решения централизованно.

Теперь вам доступна функция.

```
import { withTheme } from 'arui-feather/cn';
```

которая позволит вам получить тему из провайдера.

Не освещенная тема

```
import Button from 'arui-feater/button' // импортируется компонент, обернутый в withTheme и импортируются стили
import Button from 'arui-feater/button/button' // импортируется компонент обернутый в withTheme
import { Button } from 'arui-feater/button/button' // импортируется компонент без css
import { Button } from 'arui-feater/button' // импортируется компонент c css но без withTheme
```

## @performance больше не нужен

Много кто спрашивал что за архаизм @performance что есть же React.PureComponent
Во времена  [cn-decorator](https://github.com/alfa-laboratory/cn-decorator) 
Вам необходимо было обернуть ваш компонент декоратором [@performance](https://github.com/alfa-laboratory/arui-feather/blob/master/src/performance.js#L112)
Просто потому что @cn внутри использовал  context.theme и перерендеривал компонент в момент изменения темы, добавляя нужные классы.
Если у вас используется bem-react-classname - вам больше не нужно @performance
Используйте обычный React.PureComponent. Но если вам нужно поддержать тему в компоненте - оберните ваш компонент 
```
import { withTheme } from 'arui-feather/cn';
...
export default withTheme(MyComponent);
```
В arui-feather мы избавились от @performance()

Однако есть еще такая штука как @performance(true)
От которой нужно избавляться более аккуратно.

@performance будет считаться как deprecated и будет удалена в следующих мажорных релизах

## Stopped Component injecting support

Поскольку мы отказались от cn-decorator

Мы не используем https://github.com/alfa-laboratory/cn-decorator#di-components-
Эта функциональность не нашла поддержки у потребителей и не является больше рекомендуемой

## Removed unnecessary polyfills

arui-feather поставлял полифилов больше чем нужно для работы библиотеки. 
Для развития популярной библиотеки важно держать в ней только код нужный для ее работы.

## Мы удалили modernizr

[Modernizr](https://modernizr.com/) вызывал у нас боли с поддержкой билд утилит и пакетов для того чтоб он работал. Поэтому и отправился на покой

## @autobind

Внутри библиотеки мы больше не используем @autobind в угоду упрощения кода.

## Contribution 

Мы восстанавливаем регулярные встречи меинтейнеров и активную работу по развитию библиотеки компонентов

Наш ценности:
1) Мы не любим незакрытые вопросы
2) Задача должна быть настолько мелкой чтобы ее можно было быстро зарелизить.
3) Изменение должно затрагивать только то что нужно по задаче
4) Уважаем тех кто видит проблему и кидает PR
5) Помогаем друг другу изо всех сил

Мы ведем задачи на github.

Описали процесс контрибьюта.

Огромное спасибо всем участникам подготовки релиза

@aso1datov @SiebenSieben @RomanFadeev26 @SkripalBoris @bamaboy @doyakovlev 
@stepancar @Heymdall @aweppc @Luchanso @dmitrbrvsk

**Comment by Luchanso** [comment]
👍
