### ISSUE TITLE
Перенести jsdoc типы в ts

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#1125]
Библиотека была частично переведена на tS
Однако не везде удалили лишнее.
Предлагается пройтись по проекты и повыпиливать jsDOc типы заменяя на тайпскриптовые.

Кроме этого в этой задаче ничего делать не нужно. Только это.
Самый простой способ найти подобное
```@param {```

Все непонятные момент нужно оформлять в отдельную задачу

**Comment by Luchanso** [comment]
@stepancar Актуально?
