### ISSUE TITLE
В компоненте Select неверный border-radius

### ISSUE THREAD

**Issue by mishenkoa** [alfa-laboratory/arui-feather#1127]
Сейчас в компоненте [select](https://digital.alfabank.ru/components/select) неверный `border-radius`

## Ожидаемое поведение
У блока `popup` `border-radius` равен `0px`

## Актуальное поведение
У блока `popup` `border-radius` равен `4px`
![image](https://user-images.githubusercontent.com/20029966/78547946-52fc3f80-7819-11ea-8afc-ff187bb8202e.png)

## Шаги для воспроизведения
Открыть [витрину](https://digital.alfabank.ru/components/select) с компонентом

## Возможное решение
убрать `border-radius` в `4px`

## Окружение

* Используемая версия библиотеки: 17.5.0
* Имя и версия браузера:  Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* Имя и версия ОС: macOS catalina 10.15.2

**Comment by reme3d2y** [comment]
Там в принципе косяк с тенью и скруглением. 

![image](https://user-images.githubusercontent.com/9968618/78659085-b9de2f00-78d3-11ea-95ad-f900262bd2a4.png)

**Comment by reme3d2y** [comment]
В дизайн-макетах у попапа нет скругления.
![image](https://user-images.githubusercontent.com/9968618/78660543-f14ddb00-78d5-11ea-97be-d5edc7aef244.png)

**Comment by mishenkoa** [comment]
Обновил описание (внимание на углы попапа на скрине в секции "Актуальное поведение")

**Comment by SiebenSieben** [comment]
В более свежих макетах у попапа есть скругления, сейчас закину реквест с фиксом
