### ISSUE TITLE
Поменять rgb цвета в компоненте Plate на переменные

### ISSUE THREAD

**Issue by IBelyaev** [alfa-laboratory/arui-feather#1132]
В файле `arui-feather/src/plate/plate.css` используюются цвета, которых нет в переменных.
https://github.com/alfa-laboratory/arui-feather/pull/1131/commits/5883e7f4de88043209ec1cc5f63dc6ac934e6754#diff-9ddafdc6aa2bbae4d1df2cf7e640dcd9

Нужно добавить их в диз систему и поменять в этом файле

**Comment by SiebenSieben** [comment]
Plate теперь в core-components
