### ISSUE TITLE
Компонент CheckBox работает некорректно

### ISSUE THREAD

**Issue by slavabelaev** [alfa-laboratory/arui-feather#1136]
## Ожидания
Ожидается, что при изменении значения checked="true", компонент закрасится в красный и отобразит галочку.

## Актуальное поведение
В действительности, при изменении значения отображается только галочка, но цвет заливки не меняется. А так как галочка белая и заливка белая, то создается впечатление что компонент не работает.

## Шаги для воспроизведения
1. Создание нового проекта через ```npx create-react-app my-app```
2.  Установка пакета ```npm install arui-feather --save```
3. Добавление компонента в корневой компонент App

## Возможное решение
По видимости цвет должен меняться в элементе .checkbox__box, так как именно это и происходит если исследовать элемент в демонстрации по ссылке на GitHub.

## Окружение

* 17.5.1, обновил до ^17.7.0 но это не помогло
* Google Chrome
* Mac OS X

**Comment by prosto-lapsha** [comment]
вот тут все отрабатывает нормально https://digital.alfabank.ru/components/checkbox
может у тебя что-то переопределило стили? не заглядывал где именно цвет не проставляется?

**Comment by slavabelaev** [comment]
Я разобрался в чем проблема. По умолчанию не стоит параметр theme="alfa-on-white", поэтому если не указать этот параметр чекбокс всегда будет выглядеть белым при чеке и без него. Вот пример, результатом отображения которого будет белый чекбокс, хотя ожидается красный.
`<CheckBox checked={true} />`

**Comment by stepancar** [comment]
@slavabelaev я не понима, пример из последненго коммента
https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=%3CCheckbox%20checked=%7Btrue%7D%20/%3E
 Что тут не так?

**Comment by slavabelaev** [comment]
Довольно странная ситуация. У меня данный код отрабатывает не так как в твоем sandbox.

**Comment by stepancar** [comment]
@slavabelaev Тему у вас скорее всего установлена выше. Тема в компонент передается с помощью theme-provider
К сожалению без изолированного sandbox помочь не сможем так как проблемы не видим.
