### ISSUE TITLE
Некорректное поведение PhoneInput на вставку длинных значений

### ISSUE THREAD

**Issue by kdmatrosov** [alfa-laboratory/arui-feather#1141]
## Ожидаемое поведение

При вставке значений вида `+ 1 (111) 111-11-11` (например, +7 (999) 123-45-67) ожидаем увидеть в поле отформатированное значение `+1 111 111-11-11`

## Актуальное поведение
Реально получаем в отображении `+1 111 111-11`, то есть теряем 2 последних значимых символа.

## Причина такого поведения
PnoneInput является оберткой над MaskedInput и значение обрезается именно [внутри MaskedInput](https://github.com/alfa-laboratory/arui-feather/blob/master/src/masked-input/masked-input.tsx#L174). Это происходит в момент вставки из-за maxlength на input. В результате чего в обработчик приходит обрезанное значение `+1 (111) 111-11-`. Далее незначимые символы откидываются и мы получаем то самое ``+1 111 111-11``

## Возможное решение
Делегировать контроль за длиной значения с input в js-логику

## Окружение
Используемая версия библиотеки: 17.7.0
Компонент: PhoneInput
Имя и версия браузера: любой
Имя и версия ОС: любая

**Comment by reme3d2y** [comment]
@k
Исправлено. Думаю можно закрыть issue
