### ISSUE TITLE
Цвет знака валюты и минорной части в Amount

### ISSUE THREAD

**Issue by web-arch** [alfa-laboratory/arui-feather#1160]
Предлагаю добавить в Amount возможность менять цвет символов после запятой на тот же, что и у остальной суммы. Думаю много где это изменено чисто стилями и кажется должна быть такая возможность

Current
<img width="118" alt="Библиотека компонентов : Дизайн Альфа-Банка 2020-05-25 13-05-36" src="https://user-images.githubusercontent.com/15825498/82803077-932a8680-9e88-11ea-9db9-dc0277fcc630.png">

Expected
<img width="627" alt="ЕКП  Новая анкета – Figma 2020-05-25 11-56-52" src="https://user-images.githubusercontent.com/15825498/82801599-3e860c00-9e86-11ea-9de5-f7b08ed522f0.png">

**Comment by reme3d2y** [comment]
Минорная часть использует opacity.
Кажется, переопределение через css не должно быть проблемой?
