### ISSUE TITLE
Ошибка при обновлении до версии 18.0.0

### ISSUE THREAD

**Issue by RomanPrimolennyy** [alfa-laboratory/arui-feather#1191]
При обновлении версии компонентов с 12.12.0 в проекте до 18.0.0 возникает ошибка:
  ERROR in ./node_modules/arui-private/modal/modal.js
      Module not found: Error: Can't resolve 'arui-feather/render-in-container' 

## Ожидаемое поведение
Отсутсвие ошибки
## Возможное решение
возможно несовметимо с библиотекой "arui-private": "^9.4.7"

## Окружение

* Используемая версия библиотеки: 18.0.0
* Имя и версия браузера: Chrome Version 70.0.3538.77
* Имя и версия ОС: Windows 10

**Comment by SiebenSieben** [comment]
Вероятно, не совместимо, arui-private сейчас уже 15.9.1 )
