### ISSUE TITLE
При переходе с 12 версии на 18.0.0 окна не прижимаются к левому краю

### ISSUE THREAD

**Issue by RomanPrimolennyy** [alfa-laboratory/arui-feather#1218]
Окна должны быть прижаты к левому краю

Окна выравнены по центру(см. вложения)

Заметили, что проблема наблюдается не у всех.
## Возможное решение
Возможно проблема связана с тем, что стоит английская версия Windows 10.
У других коллег с такой же версией Chrome и бибиотеки все работает нормально. 

## Окружение

18.0.0 - версия библиотеки
Chrome - 84.0
Windows 10 Enterprise 1909
![arui](https://user-images.githubusercontent.com/63113954/95436083-1b06be00-095c-11eb-9e8c-2fc10127d9dc.png)
![OS_version](https://user-images.githubusercontent.com/63113954/95436084-1b9f5480-095c-11eb-98a2-6c535b035db2.png)
![update_to_18_version](https://user-images.githubusercontent.com/63113954/95436085-1c37eb00-095c-11eb-8317-c2fa9fd5ddee.jpg)

**Comment by SiebenSieben** [comment]
Не связано с этой библиотекой

**Comment by RomanPrimolennyy** [comment]
Когда отказываешься на 12 версию, то все ок становится.
