### ISSUE TITLE
Валидация в input

### ISSUE THREAD

**Issue by Aliaksandra-Sunny** [alfa-laboratory/arui-feather#1275]
Добрый день! Я занимаюсь разработкой frontend-части для приложения Альфа-Банка Беларуси.
Появился вопрос относительно встроенной валидации в Input, EmailInput и IntlPhoneInput. 
Подскажите, пожалуйста, как можно настроить errors в зависимости от введенного содержимого, или стоит воспользоваться дополнительной сторонней библиотекой для валидации?

**Comment by SiebenSieben** [comment]
Компоненты «тупые», валидация накручивается сверху.

Для новых проектов рекомендуем сразу использовать новую библиотеку [core-components](https://github.com/alfa-laboratory/core-components).

(Обсудили в зуме.)
