### ISSUE TITLE
Checkbox component: broken layout

### ISSUE THREAD

**Issue by forshortmrmeth** [alfa-laboratory/arui-feather#248]
При размере экрана в 320px ломается чекбокс, если в label длинный текст.

## Ожидаемое поведение
Один из двух вариантов:
![welcome aboard 2017-09-13 13-33-43](https://user-images.githubusercontent.com/7488702/30373084-cf3afb18-9888-11e7-80fb-28ee5b30f29f.png)

## Актуальное поведение
![320px checkbox](https://user-images.githubusercontent.com/7488702/30373040-ad2a0ae6-9888-11e7-86a5-59f43454681f.png)

**Comment by teryaew** [comment]
@forshortmrmeth второй вариант в ожидаемом более приемлем. Приветствуем пулл реквесты.

**Comment by teryaew** [comment]
Landed in 9.10.0.
