### ISSUE TITLE
Event object as first argument in dom event callbacks

### ISSUE THREAD

**Issue by iyromanov** [alfa-laboratory/arui-feather#295]
При совместном использовании контролов из библиотеки и ReduxForm в IE11 возникает проблема: ReduxForm ожидает, что в колбэке `onChange` первым аргументом будет приходить объект `event`, а приходит зачастую строка `newValue`. По этой причине, например в IE11  при использовании `Radio` выбрасывется Exception: `Object.defineproperty argument is not an object`

## Возможное решение
Унификация интерфейсов колбэков в контролах и передача первым аргументом объекта `event`.

## Окружение
arui-feather 9.10.4
IE 11

**Comment by stepancar** [comment]
Обсуждать будем? Собственно эвент не просовывается не просто так. Это один из принципов, используемых в этом проекте.

**Comment by stepancar** [comment]
@SiebenSieben
