### ISSUE TITLE
When using PropgressBar was getting error "React is not defined" !

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#314]
When using PropgressBar was getting error "React is not defined".

To resolve this error, I propose to replace the word "React" with "_react" in file progress-bar.js

## Окружение

* Используемая версия библиотеки: arui-feather version "10.2.1"
* Имя и версия браузера: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Имя и версия ОС: Mac OS "Siera"

**Comment by Vvtu** [comment]
Если посмотреть на код после  транспайлинга jsx, то  ошибка явно видна:

....
....
var _react = require('react');
....
....
   return React.createElement(
            'div',
            { className: cn({ size: this.props.size }) },
            React.createElement('div', {
                style: styles,
                className: cn('current-value')
            })
        );


Почему react объявлен как "_react",   а используется как "React" ?
Что транспайлер ошибся ?

**Comment by Vvtu** [comment]
Просто нужно добавить в начало файла, как в остальных модулях - import React from 'react';

**Comment by stepancar** [comment]
https://github.com/alfa-laboratory/arui-feather/issues/346
