### ISSUE TITLE
Checkbox with no text property aligns down in flexbox container.

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#321]
Checkbox with no text property aligns down in flexbox container. It is not correct.
When text property is specified (and not equal to zero string) Checkbox aligns correctly.

Окружение

Используемая версия библиотеки: arui-feather version "10.2.1"
Имя и версия браузера: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Имя и версия ОС: Mac OS "Siera"

**Comment by teryaew** [comment]
Fixed in [10.7.0](https://github.com/alfa-laboratory/arui-feather/releases/tag/v10.7.0). Thx for report.
