### ISSUE TITLE
When using popup (and other components needed setTarget functions) with React 16+ get error "_processChildContext is not available in React 16+".

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#329]
When using popup (and other components needed setTarget functions) with React 16+  get following error:

 "_processChildContext is not available in React 16+. This likely means you have multiple copies of React and are attempting to nest a React 15 tree inside a React 16 tree using unstable_renderSubtreeIntoContainer, which isn't supported. Try to make sure you have only one copy of React (and ideally, switch to ReactDOM.createPortal).".

## Шаги для воспроизведения

using  with React 16+ following code:
 componentDidMount() {
    this.popup1.setTarget(this.target1.control);
  }

## Окружение

Используемая версия библиотек: arui-feather version "10.2.1" + React 16+
Имя и версия браузера: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Имя и версия ОС: Mac OS "Siera"

**Comment by teryaew** [comment]
@Vvtu переход на React 16 в процессе, thx за репорт.

**Comment by Vvtu** [comment]
Спасибо.
Было бы хорошо перейти на 16.


С уважением,

Вячеслав Туев
+7 926 226-07-07

**Comment by teryaew** [comment]
@Vvtu React 16 support is [here](https://github.com/alfa-laboratory/arui-feather/releases/tag/v11.0.0).
