### ISSUE TITLE
Bug (or feature) in Notification component.  

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#331]
When Notification windows was opened in first time. It can be closed only if close icon clicked.  It is correct.

But when Notification windows was opened in second time it can be closed  either by close icon clicked or by click to any place notification windows.   I suppose it is not correct.  
## Ожидаемое поведение

It should show the same behavior regardless was it opened before or not.

Closing the window should only happen by icon clicking not by windows clicking no matter was the window opened and closed before.

## Шаги для воспроизведения

Use Notification   on https://github.com/alfa-laboratory/arui-feather

## Окружение
 Chrome and Safari browsers.

**Comment by teryaew** [comment]
@Vvtu
https://github.com/alfa-laboratory/arui-feather/pull/330 должен разрешить проблему

**Comment by Vvtu** [comment]
Я на сайте вижу только #329  и #331    (  #330 - скорее всего для вашего внутреннего пользования, я его не чиже)
С уважением,

Вячеслав Туев
+7 926 226-07-07

**Comment by teryaew** [comment]
Странно, поскольку этот репозиторий публичен. И я вижу этот PR в незалогиненном состоянии тоже.

**Comment by Vvtu** [comment]
С уважением,

Вячеслав Туев
+7 926 226-07-07

**Comment by Vvtu** [comment]
Я ошибся вчера. Извиняюсь.  Репозиторий публичный и мне видны все PR.
С уважением,

Вячеслав Туев
+7 926 226-07-07

**Comment by teryaew** [comment]
@Vvtu исправлено в [10.3.1](https://github.com/alfa-laboratory/arui-feather/releases/tag/v10.3.1)
