### ISSUE TITLE
В вашем демонстрационном примере использования компонента popup  ошибка: Cannot show popup without target or position

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#335]
В вашем демонстрационном примере использования компонента popup  ошибка:
Cannot show popup without target or position
    at Popup.redraw (popup.js:439)
    at Popup.setTarget (popup.js:344)

После того, как я убрал свойство "control" из 

`    componentDidMount() {
        this.popup1.setTarget(this.target1.control);
        this.popup2.setTarget(this.target2.control);
        this.popup3.setTarget(this.target3.control);
        this.popup4.setTarget(this.target4.control);
        this.popup5.setTarget(this.target5.control);
        this.popup7.setTarget(this.target7.control);
    }

`
Ошибка не появлялась. Все заработало.
Т.е. код должен быть таким:

`    componentDidMount() {
        this.popup1.setTarget(this.target1);
        this.popup2.setTarget(this.target2);
        this.popup3.setTarget(this.target3);
        this.popup4.setTarget(this.target4);
        this.popup5.setTarget(this.target5);
        this.popup7.setTarget(this.target7);
    }

`
## Окружение

* Используемая версия библиотеки: react  15.6.2, 
* Используемая версия библиотеки: arui-feather-10.3.1
* Имя и версия браузера: Chrome
* Имя и версия ОС: Mac OS Siera

**Comment by teryaew** [comment]
@Vvtu не обнаружили проблем с нескольких браузеров/машин. Поле `control` как раз должно ссылаться на `{HTMLButtonElement|HTMLSpanElement}` для привязки к нему попапа.
