### ISSUE TITLE
outsideClickClosable not working in Notification component

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#338]
outsideClickClosable not working in Notification component

## Ожидаемое поведение
Если outsideClickClosable={true} , то Notification окно должно закрываться при клике на область вне окна

## Актуальное поведение

Задан outsideClickClosable={true}. Notification окно не закрывается при клике на область вне окна

## Окружение
 React 16  (сборка Create React App)
* Используемая версия библиотеки: arui-feather-10.3.1
* Имя и версия браузера: Chrome Version 62.0.3202.75 64bit
* Имя и версия ОС: Mac OS Siera

**Comment by stepancar** [comment]
@Vvtu 
Компонент умеет вызывать обработчик события клика вне уведомления.
То есть добавление параметра outsideClickClosable={true} предполагает лишь вызов
метода onClickOutside
https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=initialState%20=%20%7B%0A%20%20%20%20visible:%20false%0A%7D;%0A%3Cdiv%3E%0A%20%20%20%20%3CButton%20onClick=%7B%20()%20=%3E%20setState(%7B%20visible:%20!state.visible%20%7D)%20%7D%3E%0A%20%20%20%20%20%20%20%20%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%D0%BF%D0%BB%D0%B0%D1%82%D1%91%D0%B6%0A%20%20%20%20%3C/Button%3E%0A%20%20%20%20%3CNotification%0A%20%20%20%20%20%20%20%20visible=%7B%20state.visible%20%7D%0A%20%20%20%20%20%20%20%20status='ok'%0A%20%20%20%20%20%20%20%20offset=%7B%2010%20%7D%0A%20%20%20%20%20%20%20%20title=%7B%20'%D0%9F%D0%BB%D0%B0%D1%82%D1%91%D0%B6%20%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD'%20%7D%0A%20%20%20%20%20%20%20%20outsideClickClosable=%7Btrue%20%7D%0A%20%20%20%20%20%20%20%20onClickOutside=%7B%20()%20=%3E%20%7B%20setState(%7B%20visible:%20false%20%7D);%20%7D%20%7D%0A%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%D0%9F%D0%BB%D0%B0%D1%82%D1%91%D0%B6%20%D0%BD%D0%B0%20%D1%81%D1%83%D0%BC%D0%BC%D1%83%20150%20000%20%E2%82%BD%20%D0%B4%D0%BB%D1%8F%20%D0%98%D0%9F%20%D0%A4%D1%80%D0%B8%D0%B4%D0%BC%D0%B0%D0%BD%20%D0%9C.%D0%9C.%20%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%0A%20%20%20%20%3C/Notification%3E%0A%3C/div%3E

Другое дело, почему для этого есть 2 параметра, хотя можно использовать один onClickOutside - обсудим и дадим ответ.

**Comment by Vvtu** [comment]
Понял,
спасибо.

С уважением,

Вячеслав Туев
+7 926 226-07-07
