### ISSUE TITLE
Проблемы с работой компонентов в IE11

### ISSUE THREAD

**Issue by cosmmm** [alfa-laboratory/arui-feather#339]
Компоненты с демонстрационного сайта https://alfa-laboratory.github.io/arui-feather/styleguide/ не работают как ожидается в InternetExplorer 11.0.9600.18125:
1. Не поддерживается работа в тёмной теме - цвет текста остаётся тёмным.
2. Attach не отображает имя выбранного файла.
3. Button не поддерживает аутлайн в :focus.
4. CalendarInput и Calendar выдают ошибку: TypeError: Объект не поддерживает свойство или метод "find".
5. CardInput не позволяет вводить цифры.
6. CheckBoxGroup и CheckBox не устанавливает значения во всех типах чекбоксов.
7. Collapse не выполняет скрытие текста.
8. Dropdown выдаёт ошибку: TypeError: Объект не поддерживает свойство или метод "is".
9. EmailInput не позволяет выполнять ввод текста.
10. FormField не позволяет выполнять ввод текста.
11. Form не позволяет выполнять ввод текста.
12. InputAutocomplete выдаёт ошибку: TypeError: Объект не поддерживает свойство или метод "is".
13. InputGroup не позволяет выполнять ввод текста.
14. Input с placeholder "Введите сумму" не позволяет выполнять ввод цифр, зато пропускает текст. Остальные виды Input не позволяют ни выполнять ввод текста, ни очищать уже введённый в примерах текст.
15. MenuItem и Menu выдают ошибку: TypeError: Объект не поддерживает свойство или метод "is".
16. MoneyInput не позволяет вводить цифры.
17. Notification не отображает всплывающее окно при нажатии на кнопку.
18. PhoneInput не позволяет вводить телефонный номер.
19. Plate не скрывается при нажатии на крестик.
20. PopupHeader и Popup выдают ошибку: TypeError: Объект не поддерживает свойство или метод "is".
21. RadioGroup и Radio не позволяет выполнять выбор радиокнопок всех видов.
22. Select и Sidebar выдают ошибку: TypeError: Объект не поддерживает свойство или метод "is".
23. SlideDown не отображает выпадающий текст.
24. Tabs не переключает закладки.
25. TagButton не включает состояние нажатой кнопки.
26. TextArea не позволяет вводить текст.
27. Use as controlled не позволяет вводить текст.

## Ожидаемое поведение
Ожидается, что все компоненты должны работать в IE11 близко к тому, как они работают в Chrome.

## Окружение

* Используемая версия библиотеки: версия с сайта https://alfa-laboratory.github.io/arui-feather/styleguide/
* Имя и версия браузера: Internet Explorer 11.0.9600.18125 с установленным Adblock Plus for IE.
* Имя и версия ОС: Windows 8.1 (версия 6.3.9600).
![arui-feather-type-error](https://user-images.githubusercontent.com/33419288/32441082-5255e35e-c30f-11e7-9656-bc2c11c0be59.png)

**Comment by teryaew** [comment]
Привет, спасибо за репорт. О проблемах в курсе, подняли приоритетность. https://github.com/alfa-laboratory/arui-feather/pull/343 должен решить большинство кейсов.
