### ISSUE TITLE
Progressbar  не работатет. 

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#346]
Progressbar  не работатет.   
## Ожидаемое поведение
Что будет работать.
## Актуальное поведение
Сообщение об ошибке:   React is undefined!
## Возможное решение
В код нужно добавить объявление реакта:  import React from 'react';

## Окружение
Сборка Create React App
* Используемая версия библиотеки: arui-feather-10.3.1
* Имя и версия браузера: Chrome
* Имя и версия ОС: MacOS Siera

**Comment by stepancar** [comment]
@Vvtu , собираете используя arui-presets?

**Comment by stepancar** [comment]
Мы используем https://github.com/alfa-laboratory/arui-presets
Ваша проблема решится если вы будете использовать 
https://github.com/alfa-laboratory/arui-presets/blob/master/webpack.base.js
Или установите себе ProvidePlugin
https://github.com/alfa-laboratory/arui-presets/blob/master/webpack.base.js#L59

**Comment by stepancar** [comment]
По поводу того, что в части компонентов используется конструкция
```
import { Component } from 'react';
```
, а в части 
```
import React from 'react';
```
Обсудим в ближайшее время. Спасибо!

**Comment by Vvtu** [comment]
> @Vvtu <https://github.com/vvtu> , собираете используя arui-presets?
> 
> 

Ваша сборка у меня, увы, не завелась.  Это конечно мои проблемы. Pyton не той версии и что-то еще.
Библиотеку arui-feather устанавливаю как npm пакет.
Для работы я использую Create React App.

Установка presets из npm  - не изменила ситуацию c ProgressBar.

Установить   webpack.ProvidePlugin тоже нет возможности. Это же Create React App  - zero config.

Пока приходиться при каждой установке любого пакета заходить в progress-bar.js  и менять “React”  на  “_react”.


С уважением,

Вячеслав Туев
+7 926 226-07-07

**Comment by stepancar** [comment]
@Vvtu , проблема должна быть решена. Установите последнюю версию. Если возникнут проблемы - сообщите нам. Спасибо.
