### ISSUE TITLE
InputAutocomplete

### ISSUE THREAD

**Issue by Shushuru** [alfa-laboratory/arui-feather#351]
При выборе одного из значений в выпадашке подставляет значения из другой выпадашки.

1. В поле "Элементы с кастомной разметкой" выбираем любое значение, например, Гипермаркет.
2. Теперь в поле "Автокомплит с автозакрытием после выбора" выбираем так же любой значение, например, Tumblr.
3. И, наконец, снова меняет значение в поле "Элементы с кастомной разметкой", например, на Автотранспорт.
**4. Получаем Twitter.**

## Окружение

* Имя и версия браузера: Safari, Version 11.0.1 (12604.3.5.1.1)
* Имя и версия ОС: Sierra 10.12.6 (16G29)

**Comment by teryaew** [comment]
Спасибо за репорт. Исправлено в https://github.com/alfa-laboratory/arui-feather/pull/359.
