### ISSUE TITLE
Textarea falls with error in React16. It works fine in React15.

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#355]
Textarea falls with error in React16. It works fine in React15.

The error is:
ReactBaseClasses.js:64 Uncaught TypeError: this.updater.enqueueCallback is not a function
    at TextareaAutosize../node_modules/arui-feather/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (ReactBaseClasses.js:64)
    at 

## Актуальное поведение
Textarea falls with error in React16.

## Окружение

* Используемая версия библиотеки: arui-feather-10.3.1
* Имя и версия браузера: Chrome Version 62.0.3202.89 (Official Build) (64-bit)
* Имя и версия ОС: Mac OS Siera High

**Comment by teryaew** [comment]
@Vvtu React 16 support is [here](https://github.com/alfa-laboratory/arui-feather/releases/tag/v11.0.0).
