### ISSUE TITLE
Иконка смещена относительно центра кнопки

### ISSUE THREAD

**Issue by VsevolodTrofimov** [alfa-laboratory/arui-feather#358]
## Ожидаемое поведение
Выравнивание по центру
## Актуальное поведение
![image](https://user-images.githubusercontent.com/10118898/32720457-ade25b52-c874-11e7-8ee9-1a9aeb8f515d.png)

## Окружение

* Используемая версия библиотеки:
Demo
* Имя и версия браузера:
Yandex 17.10
* Имя и версия ОС:
Windows 10

**Comment by teryaew** [comment]
Спасибо за репорт. Исправлено в [10.5.1](https://github.com/alfa-laboratory/arui-feather/releases/tag/v10.5.1).
