### ISSUE TITLE
При использование <Checkbox  size="s" text="Name" ... /> , иконка чекбокса наезжает на текст.  

### ISSUE THREAD

**Issue by Vvtu** [alfa-laboratory/arui-feather#360]
При использование <Checkbox  size="s" text="Name" ... /> , иконка чекбокса наезжает на текст.  
Т.е квадратик чекбокса оказывается под текстом, указанным в свойстве "text".
И при этом размер шрифта не соответсвует "s", а соответсвует "m" !

При использовании точно такого же кода, но с size="m"  или с size="l" - все работает корректно. Ничего не наезжает.

## Ожидаемое поведение
При изпользовании <Checkbox  size="s" text="Name" ... />  текст не наезжал на чекбокс.

## Актуальное поведение

![screen shot 2017-11-14 at 11 23 42](https://user-images.githubusercontent.com/5857477/32769989-0b6f9e50-c92f-11e7-884d-9e382f2b73fd.png)

## Возможное решение

Возможно, это проблема с шрифтами Mac OS

## Окружение

Сборка  -  Create React App  ,  React 16+
* Используемая версия библиотеки: "arui-feather":   version: 10.5.0 - установлена как npm пакет
* Имя и версия браузера:  
Chrome Version 62.0.3202.89 (Official Build) (64-bit)
Safari Version 11.0.1 (13604.3.5)
Firefox Quantum 57  64bit

* Имя и версия ОС: Mac OS Siera High

**Comment by Vvtu** [comment]
<img width="401" alt="screen shot 2017-11-14 at 11 56 20" src="https://user-images.githubusercontent.com/5857477/32771181-f5c07152-c932-11e7-8f07-3033c7af6e6f.png">

Вот, при использовании такого кода, происходит наезжание текста на чекбокс.

**Comment by teryaew** [comment]
@Vvtu в `<CheckBox />` и `<Radio />` с `type: 'normal'` у нас никогда не было размеров `s` и `xl` — из-за ненадобности. Если всё-таки какой-то размер показался нужным — то давайте посмотрим интерфейс в целом где это может использоваться и внесём правки: либо в этот интерфейс, либо в библиотеку компонентов.

**Comment by Vvtu** [comment]
Размер s очень нужен и xl нужен. Если сделаете, то будет хорошо.

**Comment by teryaew** [comment]
@Vvtu можно плиз пример интерфейса (макетом например) где реально предполагается использовать данные размерности?

**Comment by Vvtu** [comment]
Размер 'xl' приходиться применять для мобильной версии.
А размер 's' для десктопов с большим монитором.
В общем, на ваше усмотрение конечно.
Если эти размеры для некоторых элементов не будут предусмотрены, то значит так надо. Нужно только этот факт отразить в документации.

**Comment by teryaew** [comment]
Один из принципов разработки данной библиотеки — [YAGNI](https://github.com/alfa-laboratory/arui-feather/blob/master/CONTRIBUTION.md#Принципы-разработки), до этого момента просто не было запроса на такие размеры. Если реально нужно (давайте посмотрим дизайн)  — то добавить совсем не проблема.

**Comment by Vvtu** [comment]
Реально пока не нужно.

**Comment by teryaew** [comment]
Хорошо, тогда пока закрываю ишью, а когда потребуется — мы приветствуем пулл реквесты.

**Comment by Vvtu** [comment]
Было бы хорошо для (development mode) получать сообщения в консоль, что такой size не прудусмотрен. А то потратишь много времени, пока поймешь из за чего произошла ошибка.
