### ISSUE TITLE
Input с заголовком. При автозаполнении паролей браузером заголовок закрывает предзаполненные данные

### ISSUE THREAD

**Issue by lskaleksandr** [alfa-laboratory/arui-feather#361]
При использовании Input'a с заголовком для паролей возникает UI баг. При автозаполнении паролей браузером(chrome) заголовок закрывает предзаполненные данные.
В браузере FF данное поведение актуально так же и при предзаполение логина.
## Ожидаемое поведение
При автозаполнении паролей браузером заголовок не должен закрывать поле с предзаполненным паролем (2.jpg)
## Актуальное поведение
При автозаполнении паролей браузером заголовок закрывает предзаполненные данные (1.jpg) 
![1](https://user-images.githubusercontent.com/30446589/32779866-563d4786-c950-11e7-8c03-cf2f4ff8787f.JPG)
При клике на любое место на странице, отображение становится нормальным (2.jpg)
![2](https://user-images.githubusercontent.com/30446589/32779869-59147b46-c950-11e7-8c36-c56f4d77e589.JPG)

## Шаги для воспроизведения
1. Ввести пароль в Input с заголовком type= password и залогиниться в приложение.
2. Сохранить пароль в браузере.
3. Выполнить Logout и заново открыть страницу логина.
## Окружение

* Используемая версия библиотеки: 
10.1.2
* Имя и версия браузера: chrome только для паролей, FF при любом прездаполении (не только пароль)
* Имя и версия ОС: Windows 7

**Comment by teryaew** [comment]
@lskaleksandr можно ещё подробностей для воспроизведения?

идеально если на примере расшаришь, типа так:
http://localhost:8080/#playground/code=%3Cform%20method='post'%20autoComplete='on'%3E%0A%20%20%3CInput%0A%20%20%20%20label='%D0%9F%D0%B0%D1%80%D0%BE%D0%BB%D1%8C'%0A%20%20%20%20autocomplete=%7B%20true%20%7D%20%0A%20%20%20%20type='password'%0A%20%20%20%20size='xl'%0A%20%20/%3E%0A%3C/form%3E

**Comment by teryaew** [comment]
@lskaleksandr 
Проблема на уровне браузеров, даже не React:
https://stackoverflow.com/questions/11708092/detecting-browser-autofill/11710295#11710295

Сделали пару попыток с workarounds, но оптимального и кроссбраузерного решения нет:
https://github.com/alfa-laboratory/arui-feather/pull/447 (firefox только)
https://github.com/alfa-laboratory/arui-feather/pull/408 (webkits только)

Есть надежда что React в своих синтетические событиях будет отрабатывать этот кейс:
https://github.com/facebook/react/issues/11097

А пока можно лишь посоветовать использовать workaround с декоратором:
https://github.com/facebook/react/issues/1159#issuecomment-331952379
