### ISSUE TITLE
В элементе Plate с темной темой текст белого цвета

### ISSUE THREAD

**Issue by Vitegor** [alfa-laboratory/arui-feather#432]
На демо странице в элементе Plate с темной темой текст белого цвета.
Проверил только в последних версиях Google Chrome, Firefox.
![image](https://user-images.githubusercontent.com/8503289/34358517-75ce9a6e-ea61-11e7-9d9a-516071dace17.png)

**Comment by teryaew** [comment]
@Vitegor спасибо за репорт. Исправлено в [11.4.0](https://github.com/alfa-laboratory/arui-feather/releases/tag/v11.4.0).
