### ISSUE TITLE
При клике на "view code" выскакивает ошибка

### ISSUE THREAD

**Issue by VsevolodKurochka** [alfa-laboratory/arui-feather#440]
Вот ошибка, которая выскакивает при клике на кнопку "view code" у любого компонента: http://prntscr.com/hsswpd
## Ожидаемое поведение
Показать код, который есть
## Актуальное поведение
http://prntscr.com/hsswpd
## Шаги для воспроизведения
1. https://alfa-laboratory.github.io/arui-feather/styleguide/#attach - открыть ссылку
2. http://prntscr.com/hssy38 - нажать на ссылку
## Окружение

* Используемая версия библиотеки:
* Имя и версия браузера:
Версия 63.0.3239.84 (Официальная сборка), (64 бит)
* Имя и версия ОС:
Windows 10

**Comment by teryaew** [comment]
Проблема только в прод сборке, разбираемся.

**Comment by Luchanso** [comment]
@teryaew, проблема в демо тоже есть, думаю это как - то связано с этим коммитом и этим кодом https://github.com/alfa-laboratory/arui-feather/commit/1455dc601e16aa6a85ad8321a705d5906771f6f0#diff-fb70eb9128600dab5661c52f2e22770aR22

**Comment by teryaew** [comment]
@Luchanso нет, стреляет локально в прод сборке и при откатке этих изменений на 6.0.33 сейчас

**Comment by Luchanso** [comment]
@teryaew, у меня все собирается и работает всё без ошибок до этого коммита, именно с этого коммита всё перестает работать

**Comment by Luchanso** [comment]
@VsevolodKurochka спасибо за помощь, ошибка исправлена :+1:
