### ISSUE TITLE
Problem with Icon

### ISSUE THREAD

**Issue by utegaliyev** [alfa-laboratory/arui-feather#465]
## Ожидаемое поведение
 Хочу добавить Select
## Актуальное поведение
Приложение ломается
## Окружение

* Используемая версия библиотеки: 12.0.0
* Имя и версия браузера: Google Chrome 63
* Имя и версия ОС: Windows 10 64 bit

Не могу добавить Select 
import React from 'react';
import Select from 'arui-feather/select';

const options = [
    { value: '01', text: 'ИП Фридман М.М.' },
    { value: '02', text: 'ООО «Виктори»' },
    { value: '03', text: 'ФГУП НПП ВНИИЭМ' }
];

const Sample = ()=> (
    <div className='row' >
        <div className='column'>
            <Select
                size="l"
                mode='radio'
                options={ options }
            />
        </div>
    </div>
);

export default Sample;

Консоль пишет 
down.js:37 Uncaught ReferenceError: React is not defined
    at IconDown.render (down.js:37)

index.js:2177 The above error occurred in the <IconDown> component:
    in IconDown (created by Select)

Uncaught ReferenceError: React is not defined
    at IconDown.render (down.js:37)

![image](https://user-images.githubusercontent.com/5463587/34819422-e38c7070-f6e7-11e7-81c4-50411f43e2be.png)

**Comment by weivall** [comment]
у меня та же проблема 

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "arui-feather": "^12.0.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by teryaew** [comment]
@simareeno посмотри плиз, скорее всего проблема с явным импортом `React` в каждой иконке. https://github.com/alfa-laboratory/arui-feather/issues/346

**Comment by utegaliyev** [comment]
@teryaew . Да, помогло. Спасибо большое)

У меня был create-react-app. И воспользовался react-app-rewired. Тут можно делать override webpack.configs.

**Comment by simareeno** [comment]
Проблема осталась. На выходе в файле такой код:
```
var _react = require('react');
return React.createElement(_icon2.default, _extends({}, this.props, ...
```
Разумеется, React is not defined.

**Comment by simareeno** [comment]
https://github.com/webpack/webpack/issues/1054

**Comment by utegaliyev** [comment]
@simareeno  

конфиг надо поправить  в override webpack.configs

const rewireProvidePlugin = require('react-app-rewire-provide-plugin')

module.exports = function override(config, env) {
    config = rewireProvidePlugin(config, env, {React: 'react'});
    return config;
};

**Comment by vlad-zhukov** [comment]
@simareeno Похоже на то, что babel транспайлит импорты вместо вебпака. Попробуй добавить `{modules: false}` у `env` пресета.

**Comment by teryaew** [comment]
> Тут можно делать override webpack.configs.

Закрываю вопрос.
