### ISSUE TITLE
Компоненты таблицы

### ISSUE THREAD

**Issue by vlad-zhukov** [alfa-laboratory/arui-feather#468]
Сейчас нету стилей и компонентов для таблиц, было бы неплохо добавить. Что думаете?

**Comment by astandrik** [comment]
Опираясь на трудный опыт работы с таблицами, могу сказать, что таблица для всего-всего-всего (с сортировкой, пагинацией, предусмотренным функционалом поиска, фильтрации, клика, виртуального скроллинга, оптимизации перформанса и пр и пр.) достойна отдельный репы как минимум. Это мостр, который много весит, трудно тестируется и никогда не заработает так, чтобы всех удовлетворить.

Наверное целесообразнее делать узкоспециализированные таблицы в рамках каждого проекта (да вроде их особо нигде и нет сейчас так-то)

**Comment by vlad-zhukov** [comment]
Согласен, но я не предлагаю изобретать такой велосипед. Мне хотелось бы "тупые" компоненты со стилями, которые можно было бы использовать как сами по себе для простых задач, так и вместе с другими библиотеками (например [Reactabular](https://reactabular.js.org/#/))

**Comment by stepancar** [comment]
@vlad-zhukov @astandrik закрываем?

**Comment by stepancar** [comment]
@SiebenSieben please, trigger @astandrik @vlad-zhukov in your private messenger

**Comment by SiebenSieben** [comment]
Пинганул. Всё ещё есть желание добавить простой вариант для таблиц, обсуждаем.
