### ISSUE TITLE
ошибка при CalendarInput. undefined is not function

### ISSUE THREAD

**Issue by utegaliyev** [alfa-laboratory/arui-feather#481]
## Ожидаемое поведение
рендерить компонент для выбора даты
## Актуальное поведение
ломается вся страница
## Шаги для воспроизведения
Добавить CalendarInput

## Окружение

* Используемая версия библиотеки:
* Имя и версия браузера:  UC 11.5
* Имя и версия ОС: Android 7.1

![screenshot_20180114-163250](https://user-images.githubusercontent.com/5463587/34988774-1df2b872-faea-11e7-8643-502ba67c2b1b.jpg)

**Comment by artptr** [comment]
У вас в проекте подключены полифиллы?

**Comment by utegaliyev** [comment]
@artptr 
добавил только arui-presets

**Comment by artptr** [comment]
Нужно заимпортировать `arui-feather/polyfills` или подключить аналогичные свои по необходимости.

**Comment by utegaliyev** [comment]
@artptr Спасибо, большое. Помогло
