### ISSUE TITLE
Npm install cause errors

### ISSUE THREAD

**Issue by stswoon** [alfa-laboratory/arui-feather#51]
После команды npm i получаю ошибки.

## Ожидаемое поведение
Зависимости скачиваются без ошибок

## Актуальное поведение
Ошибки
1. Can't find Python executable "python"
2. install the .NET Framework 2.0 SDK

## Шаги для воспроизведения

1. npm i
```
> png-img@2.1.1 install C:\work\git\arui-feather\node_modules\png-img
> node-gyp rebuild
C:\work\git\arui-feather\node_modules\png-img>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:401:14)
...
```
2. устанавливаем питон именно 2х и добавляем в параметры PYTHON=C:\Python27\python.exe
3. снова npm i 
```
> png-img@2.1.1 install C:\work\git\arui-feather\node_modules\png-img
> node-gyp rebuild
C:\work\git\arui-feather\node_modules\png-img>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\work\git\arui-feather\node_modules\png-img\build\b
inding.sln]
...
```

## Возможное решение
Мне помогло npm install --global --production windows-build-tools, оно устанавливает питон и .NET SDK. Т.е. вероятно п.2 из тест кейса можно не делать теперь. 
Предлагаю добавить эту строчку в документацию. Либо вероятно можно еще сделать автоматическую проверку операционной системы через node и доставлять зависимость автоматически.

Литература
- https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies
- https://toster.ru/q/100471
- https://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm

## Окружение
* Используемая версия библиотеки: master и 5.0.1
* Имя и версия браузера: не важно
* Имя и версия ОС: windows7

## PS
На всякий случай хочу сообщить, т.к. не стал заводить багу, т.к. я пока еще не понял моя это проблема или нет. В конце концов после npm run demo получаю уже в chrome ошибки и соответственно не могу посмотреть примеры.
```
Module build failed: SyntaxError: C:/work/git/arui-feather/.build/prebuild/user/index.jsx: Bad character escape sequence (8:53)
   6 | import RedBox from 'redbox-react';
   7 | 
>  8 | const Demo = require('C:\work\git\arui-feather\demo\user\demo').default;
```

**Comment by stepancar** [comment]
@stswoon проблема с путями на windows известна. На данный момент мигрируем на styleguidist
запускайте 
npm run styleguide
localhost:3013 
или смотрите тут https://alfa-laboratory.github.io/arui-feather/arui-demo/styleguide/

На данный момент много компонентов уже перенесены.

**Comment by stepancar** [comment]
По проблеме с npm i - будем обсуждать

**Comment by stswoon** [comment]
node v.6.4.0.
npm v.3.10.3

**Comment by artptr** [comment]
То, что требуются python и build tools — это от [node-gyp](https://github.com/nodejs/node-gyp#on-windows). А тот, в свою очередь, требуется, в частности, для сборки node-zopfli (зависимость compression-webpack-plugin).

**Comment by teryaew** [comment]
@stswoon актуальна ли сейчас проблема?

**Comment by stswoon** [comment]
Да, но для меня не критично, можно закрыть. Если что лог:
[npm-debug.log](https://github.com/alfa-laboratory/arui-feather/files/1390098/npm-debug.log)

**Comment by teryaew** [comment]
@stswoon можешь проверить в своих условиях?

https://github.com/gemini-testing/gemini/issues/803
https://github.com/nodejs/node-gyp#on-windows

**Comment by artptr** [comment]
Кажется, issue нужно закрыть, потому что это не проблема библиотеки. Настройку рабочего окружения под Windows можно описать в Confluence.
