### ISSUE TITLE
CalendarInput - убивает конверсию

### ISSUE THREAD

**Issue by ershov-ilya** [alfa-laboratory/arui-feather#617]
Компонент CalendarInput - убивает конверсию. Проводили анализ, внутри команды, а также аналитики из BCG. Достаточно долгое время наблюдаем, что в нашей анкете по кредитным картам (есть информация, подтверждающая такую же ситуацию и в других онлайн-анкетах) на полях ввода с типом CalendarInput большие потери конверсии.

## Актуальное поведение
К поведению на десктопах претензий нет. В мобильных устройствах выскакивает нативный popup в котором человеку приходится разобраться, как перемотать календарь с текущей даты на дату своего рождения. Неоднократно на Demo наблюдали, как испытуемые в Android устройствах в нативном календаре искали год своего рождения перелистывая календарь - помесячно!  

## Ожидаемое поведение
Команда и BCG хотят видеть простое поле ввода (input) с маской ДД.ММ.ГГГГ без всплывающих окон, с простым вводом даты с помощью клавиатуры.
Использование `mobileMode: 'popup'` так же не устраивает.

## Шаги для воспроизведения
Компонент CalendarInput в мобильных устройствах Android, необходимо перелистать на 30-40 лет назад, с учётом, что "вы не догадались, что можно нажать на цифру года"

## Возможное решение

Нам нужен третий режим поведения поля: `input` 
```
// Управление нативным режимом на мобильных устройствах
mobileMode: Type.oneOf(['native', 'popup', 'input']),
```
при котором при фокусе на поле не выскакивало бы никаких попапов.
Хотим видеть простое поле ввода (input) с маской ДД.ММ.ГГГГ без всплывающих окон, с простым вводом даты с помощью клавиатуры.

## Окружение

* Используемая версия библиотеки:
12.5.0
* Имя и версия браузера:
Браузеры на мобильных устройствах
* Имя и версия ОС:
Мобильные устройства Android

**Comment by ershov-ilya** [comment]
upd: Коллеги, нам с этим изменением в эту пятницу идти на Demo с Майклом Тачем

**Comment by artptr** [comment]
Проблема решена? Можно закрывать?

**Comment by stepancar** [comment]
я так понимаю, что да
