### ISSUE TITLE
CalendarInput - у popup'а в мобильном виде не работает кнопка close

### ISSUE THREAD

**Issue by ershov-ilya** [alfa-laboratory/arui-feather#620]
CalendarInput - у popup'а с календарём в мобильном виде не работает кнопка close (крестик)

## Шаги для воспроизведения
1) Мобильный вид в Chrome
2) CalendarInput без фолбэка на нативный контрол на мобильном устройстве (mobileMode='popup')
3) Фокус в поле - открывается календарь
4) Календарь не закрывается нажатием на крестик

## Возможное решение

- Либо фиксить крестик
- Либо крестик не показывать

## Окружение

* Используемая версия библиотеки:
12.5.0
* Имя и версия браузера:
Chrome Версия 65.0.3325.181 (Официальная сборка), (64 бит)
* Имя и версия ОС:
macOS High Sierra, Версия 10.13.4

**Comment by stepancar** [comment]
@SiebenSieben не показываем или фиксим крестик?

**Comment by stepancar** [comment]
@Kokatsuna добавь сюда Артема Кислова, плиз

**Comment by SiebenSieben** [comment]
Нужно фиксить, иначе можно будет закрыть только выбором даты, что недостаточно очевидно.
