### ISSUE TITLE
Notification компонент не работает в safari 11

### ISSUE THREAD

**Issue by pumano** [alfa-laboratory/arui-feather#642]
Notification компонент не работает в safari 11
## Ожидаемое поведение
Компонент показывается и отрабатывает правильно в safari
## Актуальное поведение
Компонент вообще не показывается, но классы к элементам применяются и отрабатывают
## Шаги для воспроизведения
1) Зайти под safari на сайт: http://design.alfabank.ru/components/notification
2) Нажать на "Отправить платеж"
3) Ждать появления уведомления
## Окружение

* Используемая версия библиотеки: та что у вас на сайте: http://design.alfabank.ru/components/notification
* Имя и версия браузера: Safari 11.1 (13605.1.33.1.2)
* Имя и версия ОС: Mac OS (High Sierra)

**Comment by stepancar** [comment]
@Kokatsuna  Возьмешь в работку?

**Comment by Kokatsuna** [comment]
Попробую посмотреть @stepancar

**Comment by kino6052** [comment]
@Kokatsuna 
Заметил очень странное поведение. Если пройтись в dev tools, то перебирая все значения visibility, notification снова работает.
![kapture 2018-06-27 at 18 43 43](https://user-images.githubusercontent.com/9941024/41985103-12774d20-7a3b-11e8-8200-3a63cdc651f1.gif)
