### ISSUE TITLE
[Вопрос] Ожидается ли смена идеологии при создании компонентов?

### ISSUE THREAD

**Issue by vasivas** [alfa-laboratory/arui-feather#661]
Первым делом хочу извинится за создания обычного вопроса, а вторым за тон, который может кому-то показаться завышенным. Дело вот в чем...

Узнав о Ваших компонентах, я обрадовался, так как мне очень понравился их стиль, но когда я  открыл инструменты разработчиков на сайте со styleguide, то испытал легкий шок.
Select, я буду говорить только о нем, другое не смотрел, создан с помощью iframe...
Разве это Вам не кажется дико? 

И вот исходя из этого у меня вопрос - будите ли Вы пересматривать идеологию разработки компонентов настолько, что она позволит избавится от этого ужаса? Кому такое вообще в голову могло придти... И если Вы хотите все переписать ,то как скоро это ожидать?

**Comment by artptr** [comment]
А в чём собственно дикость? iframe некошерен? Сейчас выглядит так, что вы посмотрели только селект, не разобрались, по какой причине в нём используется пустой (!) iframe, экстраполировали его использование на всю библиотеку и объявили это её идеологией?

Как бы то ни было, iframe применён в компоненте [ResizeSensor](https://github.com/alfa-laboratory/arui-feather/blob/master/src/resize-sensor/resize-sensor.jsx), который используется для детекта изменения размеров родительского компонента. Да, это своего рода хак. Есть идеи сделать по-другому?

И зачем всю библиотеку-то переписывать?

**Comment by vasivas** [comment]
А в чём собственно дикость? iframe 

> некошерен?
Ну так iframe это очень и очень накладно, да идеологически создавать новый документ для отслеживания ресайза в  2018 году, это точно не плюс. 

>  Сейчас выглядит так, что вы посмотрели только селект, не разобрались, по какой причине в нём используется пустой (!) iframe, экстраполировали его использование на всю библиотеку и объявили это её идеологией?

С первой половиной Вы оказались правы,  а со второй можно поспорить. То что select'у требуется знать,когда его родитель изменяет размеры,  это более чем не стандартно. Хотя, признаюсь, использование нативного select для меня тоже не совсем стандартно, поэтому если необходимость в механизме ресайза продиктована использованием нативного select, то я извиняюсь, хотя и не понимаю зачем он нужен. Иначе я придерживаюсь мнения что select который зависит от размеров контейнеров выше по дереву, нестандартно. Такой подход может быть продиктован только нестандартной логикой мышления, которая просто не может не отразится на всю библиотеку. Зачем нужно знать о изменении размеров? Разве не проще это реализовать с помощью css или более подходящих для этого механизмов самого реакта (cloneNode, hoc)?

**Comment by artptr** [comment]
Это нужно для правильной перерисовки селектовой выпадайки. Она отрисовывается отдельно от базовой части контрола, чтобы предотвратить нежелательные эффекты перекрытия и позиционирования. При изменении размеров окна браузера попап может быть перерисован в другом положении, например, над контролом. С помощью css это отследить не получится.

**Comment by vasivas** [comment]
@artptr я себе слабо представляю то, о чем Вы говорите, но если Вы описываете картину, когда, предположим, select находится почти в самом низу экрана и я его открываю, то список откроется таким образом, чтобы полностью поместится во вьюпорте. Это нормально и делается это очень просто и для этого Ваш механизм не нужен. Но вот если я при открытом списке начну крутить скролл или ресайзить страницу... Вы об этом? Если да, зачем перерисовывать, когда просто напросто нужно закрыть? Ведь как при скролле так и при ресайзе фокус теряется , что должно повлечь за собой закрытие select. Разве это не логично?

И на самом деле, я давно для себя вывел правило, что лучшее должно быть очень простым. Если архитектура в какой-то момент становится сложной, то значит где-то что-то пошло не так. Кроме того ресайз больше будет напрягать посетителей. Все эти красивости и прочее производят впечатление только в единичном контексте (демо). В реальности они  напрягают. Хотя Вы это и сами понимаете.
