### ISSUE TITLE
Проблема с отображением CalendarInput

### ISSUE THREAD

**Issue by qairjar** [alfa-laboratory/arui-feather#681]
При отображение компонента CalendarInput выводится ошибка:
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

**Comment by qairjar** [comment]
@BNursultan 
import React,{Component} from 'react';
import ReactDOM from 'react-dom';
import "./index.css";
import CalendarInput from 'arui-feather/calendar-input';

class App extends React.Component {

  constructor(props) {
    super(props);
    this.state={ 
        value:"",
    }
  }

    render() {
        return (<div>
    {
        ['s', 'm', 'l', 'xl'].map(size => (
            <div className='row' key={ size }>
                <CalendarInput
                    size={ size }
                    defaultValue='01.02.2016'
                />
            </div>
        ))
    }
</div>)
    }

}

export default App;

**Comment by BNursultan** [comment]
@qairjar Вот здесь все работает:
arui-feather@latest
[Repl](https://repl.it/repls/AccurateFlakyCurrencies).

Вот этот момент странный в вашем примере:
```
import ReactDOM from 'react-dom';
```
Хотелось бы увидеть файл, где вы рендерите `App` через `ReactDOM`

**Comment by stepancar** [comment]
@qairjar
