### ISSUE TITLE
У ссылок с иконкой при переносе строки текст находится под иконкой

### ISSUE THREAD

**Issue by jangot** [alfa-laboratory/arui-feather#694]
Бывают ситуации когда надо использовать ссылку не в тексте, а независимо. Допустим у нас есть список ссылок (список pdf документов). Тогда они идут одна под одной. Если название файла длинное и оно не помещается в одну строку и переносится. Новая строка находится под иконкой. Хочется, что бы текст начинался с того-же места что и в первой строке.
Можно было бы разрулить это добавив класс иконке, но это не получается, так как иконка оборачивается с `span`, а этому элементу класс добавить нельзя.

**Comment by stepancar** [comment]
@SiebenSieben что мы можем тут сделать?

**Comment by stepancar** [comment]
@jangot В любом случае, удалось ведь переопределить поведение этого спана на проекте?

**Comment by SiebenSieben** [comment]
@stepancar 

Вариант — добавить модификацию:
display: Type.oneOf(['inline', 'block'])

Над названием можно ещё подумать.

**Comment by SiebenSieben** [comment]
Кажется, что когда у ссылки есть иконка, то чаще всего нужны именно такие стили.

**Comment by stepancar** [comment]
@jangot Feel free for PR
