### ISSUE TITLE
Необходимо перейти на `postcss-css-variables`

### ISSUE THREAD

**Issue by ivansky** [alfa-laboratory/arui-feather#704]
Переменные (custom properties) работают не так как ожидается.

```
.block {
    --modal-width: 660px;
    --border-radius: 8px;

    @media (--small-only) {
        --modal-width: 100%;
        --border-radius: 0;
    }

    &__element {
        width: var(--modal-width);
        border-radius: var(--border-radius);
    }
}
```

## Ожидаемое поведение
```
.block__element {
    width: 660px;
    border-radius: 8px;
}

@media (--small-only) {
    .block__element {
        width: 100%;
        border-radius: 0;
    }
}
```
## Актуальное поведение
```
.block__element {
    width: var(--modal-width);
    border-radius: var(--border-radius);
}
```
## Возможное решение
Перейти с [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties)  на [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables)

**Comment by ivansky** [comment]
Сравнение этих двух библиотек 
http://cssvars.atspace.cc/

**Comment by dmitriy-novikov** [comment]
а в чем проблема? браузеры, которые поддерживают переменные (например последний хром) - работают с переменными. в других браузерах отображается так, как в "ожидаемом поведении".

**Comment by ivansky** [comment]
@dmitriy-novikov В самом посте есть информация `Ожидаемое поведение` и `Актуальное поведение`. В текущем варианте у нас нет поддержки переменных внутри классов. 
`postcss-custom-properties` - довольно обрезанная реализация css переменных.

**Comment by SiebenSieben** [comment]
У postcss-custom-properties у нас сейчас в конфиге preserve false, т.е. переменные вообще вырезаются.

Теоретически сломаться ничего не должно, но до конца непонятно почему сейчас именно так.

**Comment by stepancar** [comment]
@SiebenSieben 
https://github.com/alfa-laboratory/arui-presets/pull/137
