### ISSUE TITLE
Запретить горизонтальный скролл для обрезанного текста в инпуте

### ISSUE THREAD

**Issue by mixail-novikov** [alfa-laboratory/arui-feather#708]
https://design.alfabank.ru/components/input
После того как длинный текст скрыт троеточием, его можно проскроллить с тачпада

## Ожидаемое поведение
Текст нельзя проскроллить, пока не будет поставлен курсор в поле

## Актуальное поведение
Текст можно скроллить, из-за этого видно пустоту справа после скролла

## Шаги для воспроизведения
1. Добавить длинный текст в инпут
2. Убрать курсор - появится троеточие
3. Навести на инпут и проскроллить с тачпада горизонтально

## Окружение

* Используемая версия библиотеки: https://design.alfabank.ru/
* Имя и версия браузера: Google Chrome, Версия 68.0.3440.106 (Официальная сборка), (64 бит)
* Имя и версия ОС: macOS High Sierra

**Comment by theaklair** [comment]
Не смог отследить событие скролла в `input` никаким образом.

**Comment by SchDen** [comment]
Срабатывает событие `mousewheel` - пробовал на трэкпаде макбука

**Comment by SchDen** [comment]
Попробовал реализовать за счет такого кода в компоненте инпута:
```
/**
 * Разблокирует возможность скролла в поле ввода
 *
 * @public
 * @returns {void}
 */
enableMouseWheel() {
    const input = this.control instanceof MaskedInput ? this.control.input : this.control;

    input.onwheel = () => true;
}

/**
 * Блокирует возможность скролла в поле ввода
 *
 * @public
 * @returns {void}
 */
disableMouseWheel() {
    const input = this.control instanceof MaskedInput ? this.control.getControl() : this.control;

    input.onwheel = () => false;
}
```
которые вызываются соответсвенно на focus и blur.
Для обычного инпута все работает корректно, но на инпуте с маской прокрутка просто перестает работать и с фокусом и без него. Пока разбираюсь, может у кого есть какие то идеи почему так происходит?

**Comment by SchDen** [comment]
Немного некорректно написал, с маской хорошо работает, есть нюансы с полем типа `number`

**Comment by SchDen** [comment]
Полем типа `number` такой тип "скрола" работает как управление счетчиком (инкремент, декремент значения). Думаю это корректное поведение.
