### ISSUE TITLE
Иконка съезжает

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/arui-feather#724]
Иконка в кнопке съезжает в крайнюю левую часть, раньше всё было нормально

![image](https://user-images.githubusercontent.com/2098777/45930941-f7d46600-bf6e-11e8-83df-a62981deb649.png)

```jsx
<Button icon={<IconFormatPdf size="s" />} width="available">
    Скачать
</Button>
```

**Comment by Luchanso** [comment]
Версия arui-feather@12.11.1

**Comment by danakt** [comment]
«Раньше» это примерно когда?
