### ISSUE TITLE
Ошибка при установке зависимостей

### ISSUE THREAD

**Issue by ilyar** [alfa-laboratory/arui-feather#771]
Ошибка при установке зависимостей в `node` 5, 6, 10, 11

## Ожидаемое поведение

Зависимости устанавливаются без ошибок в `node` 5+

## Актуальное поведение

Зависимости устанавливаются только в `node` 8

https://travis-ci.org/ilyar/arui-feather/builds/479844741

## Шаги для воспроизведения
```
git clone 
git submodule update --init --recursive
npm i
```
## Возможное решение

Как вариант обновить документацию и указать в каких версиях `node` будет работать.

```diff
diff --git a/README.md b/README.md
--- a/README.md
+++ b/README.md
@@ -74,7 +74,7 @@ npm install arui-feather --save
 
 Необходимые внешние зависимости системы:
 
-`node` 5+ и `npm` (https://nodejs.org/en/).
+`node` 8 и `npm` (https://nodejs.org/en/).
 
diff --git a/package.json b/package.json
--- a/package.json
+++ b/package.json
@@ -82,6 +82,9 @@
   ],
   "author": "Good guys from Alfa Laboratory",
   "license": "MPL-2.0",
+  "engines": {
+    "node": "=8"
+  },
```

## Окружение

* Используемая версия библиотеки: `master`
* `node` 5, 6, 10, 11

**Comment by ilyamilosevic** [comment]
Поддерживаю. Та же проблема возникла. Решил установкой v8.15.1.
