### ISSUE TITLE
[Вопрос] Чем собран сайт design.alfabank.ru?

### ISSUE THREAD

**Issue by ilyar** [alfa-laboratory/arui-feather#772]
Не нашел его исходников, видимо что-то свое, пожалуйста расскажите о подходе и задействованных инструментах.

**Comment by SiebenSieben** [comment]
Да, что-то своё, на реакте.
Витрина компонентов — кастомизированный styleguidist.
Большая часть контента добавляется в маркдауне и конвертируется markdown-to-jsx.
Или какие инструменты интересуют?
