### ISSUE TITLE
Отсутствует команда quality-check

### ISSUE THREAD

**Issue by bobrovnikov** [alfa-laboratory/arui-feather#798]
README.md упоминает возможность запуска `npm run quality-check`, но такой команды в package.json  не описано. Поиск по проекту тоже ничего не дал: https://github.com/alfa-laboratory/arui-feather/search?q=quality-check&unscoped_q=quality-check

**Comment by stepancar** [comment]
@bobrovnikov спасибо. Реквест на правку документации кинете?

**Comment by bobrovnikov** [comment]
@stepancar, могу. Тут скорее вопрос в чём:
1. Мы удаляем упоминание этой команды?
2. Или добавим саму команду? Она-то вроде полезная. У меня самого сейчас на проекте используется npm run test = npm run lint + npm run karma + что-то ещё.
В данном случае будет `"quality-check": "npm run lint && npm run test"`, например

**Comment by SiebenSieben** [comment]
@bobrovnikov любой вариант исправит issue ) но без quality-check вроде никто не страдает
