### ISSUE TITLE
Документация. Отсутствует возможность просмотра всего списка компонентов до обновления страницы.

### ISSUE THREAD

**Issue by VladislavDoremi** [alfa-laboratory/arui-feather#822]
Документация - https://github.com/alfa-laboratory/arui-feather/issues

Проблема: Отсутствует возможность просмотра всего списка компонентов до обновления страницы.

Причина: Не сохраняется значение поля ввода фильтрации (с сохранением результата).

## Ожидаемое поведение
Переход на страницу компонентов с сохранением значинием поля поиска и результатами поисковой выдачи

## Актуальное поведение
Переход на страницу компонентов с очисткой значиния поля поиска и сохранением  результата поисковой выдачи (отсутствует возможность просмотра всего списка компонентов до обновления страницы)

## Шаги для воспроизведения
Шаг 1 - Переход на страницу компонентов
Шаг 2 - Ввод информации в поле фильтра ( наример input )
Шаг 3 - Переход в другой раздел
Шаг 4 - Вовзврат в разлел компонентов

## Возможное решение

Вариант 1. Сбразывать результат фильтрации после возврата на страницу.

Вариант 2. Сохранять значение поля фильтрации.

## Окружение

* Используемая версия библиотеки:
Неизвестно

* Имя и версия браузера: 
Google Chrome is up to date
Version 74.0.3729.169 (Official Build) (64-bit)

* Имя и версия ОС:
Windows 10

**Comment by stepancar** [comment]
@VladislavDoremi насколько это необходимо?
С точки зрения демки компонента - когда вы переходите по ссылке - вы попадаете на другой сайт. Восстанавливать значения styleguidist не умеет
