### ISSUE TITLE
remove @autobind decorator, use arrow function instead 

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#893]
Декораторы - боль для сборки так как стандарты расходятся, нужно доставлять тонну плагинов в разные системы.
В этом issue предлагается полностью отказаться от @autobind decorator и зменить на стрелочную функцию.
Как сказал @Heymdall , нужно обратить внимание на правило линтера по сортировке если оно заставить пересортировывать - выключить его
Если зависимости на core-decorators больше нет - выпилить в этом реквесте и core-decorators

**Comment by stepancar** [comment]
@Heymdall на встрече по дизайн системе обсуждали что можем и не юзать autobind.
На всякий случай, дублирую вопрос тут, все верно, дропаем?

**Comment by Heymdall** [comment]
Да, все так, можно дропать. Но предварительно желательно из лин ера убрать правило про сортировку методов компонентов, чтоб хэндлеры не оказывались выше рендер-методов из-за него

**Comment by stepancar** [comment]
@Heymdall , спасибо!
