### ISSUE TITLE
Remove render-in-container.jsx

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-feather#899]
https://github.com/alfa-laboratory/arui-feather/blob/master/src/render-in-container/render-in-container.jsx

устарел еще в 2017
https://github.com/alfa-laboratory/arui-feather/commit/53d9ae0630105a68393bbbb0bb1ac0fccb790970#diff-e7a6a7f555d4d280e2e62ad09ca32f0d

**Comment by Luchanso** [comment]
👍
