### ISSUE TITLE
Скачок курсора

### ISSUE THREAD

**Issue by ariran5** [alfa-laboratory/arui-feather#938]
Открываю https://digital.alfabank.ru/components/emailinput и начинаю вводить английский текст с пробелами, быстро ввожу, например, "sds df df adf df df". После этого курсор прыгает сам в начало строки и ввод далее идет в начале строки

## Ожидаемое поведение
Ожидаю что ничего прыгать не будет

## Актуальное поведение
Курсор скачет с конечной позиции в начальную

## Шаги для воспроизведения
ОБновить страницу, поставить фокус на элемент, и быстро печатать с пробелами

## Окружение

* Используемая версия библиотеки: Актуальная на данный момент
* Имя и версия браузера: Сафари
* Имя и версия ОС: mac OS X Mojave

**Comment by ariran5** [comment]
А зачем этот компонент вообще если в нем логики нет ?

**Comment by stepancar** [comment]
@ariran5 вероятнее всего хотели сделать какую-то логику и предоставить потребителю специальный компонент. Видимо на первых парах его сделали таким и ни у кого так руки и не дошли. Если у тебя есть мнение по тому каким должен быть email input - кидай PR.
То же самое и с проблемой каретки
